# vim: set fileencoding=utf-8 sw=4 ts=4 et :
""" Metrology connector Pubsub client. """
from __future__ import with_statement
import sys
import os

from twisted.application import app, service
from twisted.internet import reactor

from vigilo.common.gettext import translate
from vigilo.connector import client
_ = translate(__name__)

class ConnectorServiceMaker(object):
    """
    Creates a service that wraps everything the connector needs.
    """

    #implements(service.IServiceMaker, IPlugin)

    def makeService(self):
        """ the service that wraps everything the connector needs. """
        from vigilo.connector_metro.nodetorrdtool import NodeToRRDtoolForwarder
        from vigilo.connector.status import StatusPublisher
        from vigilo.common.conf import settings
        settings.load_module(__name__)

        from vigilo.common.logging import get_logger
        LOGGER = get_logger(__name__)

        try:
            conf_ = settings['connector-metro']['config']
        except KeyError:
            LOGGER.error(_("Please set the path to the configuration "
                "database generated by VigiConf in the settings.ini."))
            sys.exit(1)

        xmpp_client = client.client_factory(settings)

        try:
            message_consumer = NodeToRRDtoolForwarder(conf_)
        except OSError, e:
            LOGGER.exception(e)
            raise
        message_consumer.setHandlerParent(xmpp_client)

        # Statistiques
        stats_publisher = StatusPublisher(
                            message_consumer,
                            settings["connector"].get("hostname", None),
                            "vigilo-connector-metro")
        stats_publisher.setHandlerParent(xmpp_client)

        root_service = service.MultiService()
        xmpp_client.setServiceParent(root_service)
        return root_service

def do_main_program():
    """ main function designed to launch the program """
    application = service.Application('Vigilo Connector for metrology data')
    conn_service = ConnectorServiceMaker().makeService()
    conn_service.setServiceParent(application)
    app.startApplication(application, False)
    reactor.run()
    return 0

def main():
    """Lancement avec Twistd"""
    tac_file = os.path.join(os.path.dirname(__file__), "twisted_service.py")
    sys.argv[1:1] = ["-y", tac_file]
    from twisted.scripts.twistd import run
    run()

if __name__ == '__main__':
    sys.exit(main())
